baseURL = "/"
languageCode = "en-us"
title = "Sarah Whinnem – Portfolio"

theme = "md-portfolio"

[params]
    firstName = "Sarah"
    lastName = "Whinnem"
    address = "New York, NY"
    phone = "860-288-4277"
    contactNote = "Product Design Leader"
    profileImage = "img/sarah.jpg"
    email = "sarah@madysondesigns.com"
    description = "I’m a product design leader with over 15 years of experience in the design and tech world. I love to make users’ lives more delightful by breaking down and solving complex problems in simple ways."
    favicon = "images/favicon.ico"
    # what sections
    showSkills = true
    showProjects = true
    showOpenSource = true
    showPublications = true
    showExperience = true
    showEducation = true

    # showQr = true

[[params.handles]]
    name = "Twitter"
    link = "https://twitter.com/madysondesigns"

[[params.handles]]
    name = "LinkedIn"
    link = "http://www.linkedin.com/in/madysondesigns"


[[params.handles]]
    name = "GitHub"
    link = "https://github.com/madysondesigns/"

# [params.google.analytics]
#     trackerID = "XX-123446-01"
